### ISSUE TITLE
SSO AzureAD: refresh token error

### ISSUE THREAD

**Issue by sandervandegeijn** [Timshel/vaultwarden#14]
This worked before, just logging in through AzureAD:

<img width="1135" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/4df514f2-27dd-486f-bfdb-8e88c4103bc0">

<img width="726" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/593b2ea4-e4e9-4c9c-8781-306082cf84e2">

Refresh token error. Using the latest tag docker image of 6 hours ago.

**Comment by Timshel** [comment]
Hey,

Yes the refresh_token is now expected since it's used to maintain the session.
It's possible that the additional scope of `offline_access` is required cf: https://github.com/MicrosoftDocs/azure-docs/issues/17134

Will make some change to allow to config it.

**Comment by sandervandegeijn** [comment]
Okay thanks! I'll ask the IAM-team to add the scope and will retest.

**Comment by sandervandegeijn** [comment]
We have added the scope in Azure but that wasn't enough it seems; still getting the same error. Do I need to set the env var as well?

**Comment by Timshel** [comment]
The scope need to be requested by VautWarden during the authorize flow.
Already [updated](https://github.com/Timshel/vaultwarden/commit/43ec3c21f7c2ff12fb830d2f07182eb925d41fd8) the `sso-support` branch, will update the `main` soon.

**Comment by sandervandegeijn** [comment]
Okay, I've changed the config:

<img width="310" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/30e274ef-d8d7-4bee-99db-6237eaff5edd">

Error persists:

<img width="1107" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/dd7f6dc5-2879-4fbb-bdd1-998f18f700a5">

Can anybody conform it's not a pebcak case?

**Comment by Timshel** [comment]
Were you not using the docker image ?

**Comment by sandervandegeijn** [comment]
Yes idd, oidcwarden/vaultwarden-oidc:latest to be exact.

**Comment by Timshel** [comment]
> will update the `main` soon.

The `SSO_SCOPES` parameter do nothing for now without an update.

**Comment by Timshel** [comment]
`1.30-1-4` is now available : https://hub.docker.com/r/oidcwarden/vaultwarden-oidc/tags

**Comment by sandervandegeijn** [comment]
Reran the test, different error:

<img width="1207" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/4aa84986-9462-4074-a429-fe61e1361b4a">

<img width="1092" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/db096d63-c600-4f8f-acf7-c0ed81958f7f">

**Comment by Timshel** [comment]
Hum, it appears I made some over-specific implementation, it's not specified in the spec that the `refresh_token` is a JWT.

Will make some change:
 - It appears it's optional so will make it so
 - Will change the logic to continue trying to extract an expiration date if it's a JWT and otherwise fallback to something like 1 year.

**Comment by sandervandegeijn** [comment]
Okay cool, just let me know when I can test again. Will do it asap :)

**Comment by Timshel** [comment]
`1.30.1-5` is building: https://github.com/Timshel/vaultwarden/actions
Should finish in around ~30min.

**Comment by sandervandegeijn** [comment]
This is fixed!
