### ISSUE TITLE
iOS app doesn't work with oidc AzureAD

### ISSUE THREAD

**Issue by sandervandegeijn** [Timshel/vaultwarden#15]
With the latest build of this evening: signing in with the iOS app fails with the following error:

<img width="414" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/7926cdbd-a836-4d1b-9982-9e1c890bad92">

<img width="953" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/5c5fb611-f1af-4f39-a230-6e2b9a3a3ed7">

Tried on both my ipad and iphone. Can somebody confirm this?

**Comment by Timshel** [comment]
Hey,
Sorry I didn't answer before but I'm afraid I can't do much since I have no IOS devices.
I had a quick look at the application code but the error is not specific.

Someone else mention it's working on ios https://github.com/Timshel/vaultwarden/issues/12#issuecomment-1883656746.
Are you running the latest version of the app ?

**Comment by Timshel** [comment]
@Halyul  Hey could you confirm the IOS version you are running and is working with the oidc server ? :)

**Comment by Timshel** [comment]
Could try `LOG_LEVEL=debug`

**Comment by Halyul** [comment]
> @Halyul Hey could you confirm the IOS version you are running and is working with the oidc server ? :)

Tested with the envs mentioned in my submitted issue, I can login without problems on iOS devices with `oidcwarden/vaultwarden-oidc:latest-alpine`. However, I'm not using AzureAD.

**Comment by sandervandegeijn** [comment]
I will ask a couple of colleagues tomorrow to check as well to rule out n=1 :)

**Comment by sandervandegeijn** [comment]
Okay, I've asked a colleague. iOS 17.3 and latest BW app: same problem. Maybe it's the combination of AzureAD and Vaultwarden oidc? Would like to see some more testcases beside ours, but I do think we have a bug here :)

**Comment by Timshel** [comment]
I expect we do.

Just had a though are you using the `offline_access` scope to return a refresh token ?

Because if not then server might not return a `refresh_token` and it already caused issues in the web client 
cf : https://github.com/Timshel/vaultwarden/issues/16

**Comment by sandervandegeijn** [comment]
Vaultwarden was complaining about the refresh token until we added that scope. That's active now and the flow is working for everything except iOS.

**Comment by sandervandegeijn** [comment]
okay, I've made a screengrab of the login process with the error. But it contains infrastructure details I can't share publicly on github. Would it be possible to share this privately under TLP-RED?

**Comment by Timshel** [comment]
> Would it be possible to share this privately under TLP-RED? 

How can I contact you ?

**Comment by sandervandegeijn** [comment]
I haven't received an email yet, is that correct? No rush, just wondering if I missed something!

**Comment by Timshel** [comment]
Sent one again.

**Comment by sandervandegeijn** [comment]
Got it thanks!

**Comment by Timshel** [comment]
Hey,
Had a quick look and no inspiration :(. 
Working on something atm will try to check it again later.

Realized I never suggested to run the server with `LOG_LEVEL=debug`.
Should give more insight on the retrieved tokens.

**Comment by sandervandegeijn** [comment]
Tried it with the debug logging:

<img width="946" alt="image" src="https://github.com/Timshel/vaultwarden/assets/2643715/a1fd3215-0266-4516-b747-527f79bbe846">

**Comment by Halyul** [comment]
> Tried [1.30.1-9] with the debug logging:
> 
> <img alt="image" width="946" src="https://private-user-images.githubusercontent.com/2643715/300101755-a1fd3215-0266-4516-b747-527f79bbe846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjU4MDYsIm5iZiI6MTcwNjMyNTUwNiwicGF0aCI6Ii8yNjQzNzE1LzMwMDEwMTc1NS1hMWZkMzIxNS0wMjY2LTQ1MTYtYjc0Ny01MjdmNzliYmU4NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMDMxODI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZkYmY3ZmM0ZDc0OGVjZTU2NmFlNzU4ZDJmYTY0NjJkZjc2ZGIzZWUwNzQ5YTFmYzM2ZDA3OThlYmE3ODA3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KlCehFzckiSZaTZT9594_L0F3ypR-kGQI0-AqJTS4PA">
> Thanks for all the help btw!

After upgrading to the latest version of `oidcwarden/vaultwarden-oidc:latest-alpine`, I have encountered the same error on both android and ios devices, which prevents logging in using sso. The same logging entries are observed. 

Only logging in with master password is possible.

**Comment by Timshel** [comment]
> After upgrading to the latest version of oidcwarden/vaultwarden-oidc:latest-alpine, I have encountered the same error on both android and ios devices, which prevents logging in using sso. The same logging entries are observed.

I can reproduce on Android with Keycloak, I expect it's a change of url from the Bitwarden app will have a look.

**Comment by Timshel** [comment]
@Halyul ok so `1.30.1-10` is building (~40min) and should fix the issue.

@sandervandegeijn I don´t expect it to fix your issue but the debug log should change.

**Comment by Halyul** [comment]
> @Halyul ok so `1.30.1-10` is building (~40min) and should fix the issue.

Can confirm it is now back to normal on both ios and android devices.

**Comment by sandervandegeijn** [comment]
@Timshel I have mail you a logfile with some relevant errors. I hope this helps :)

**Comment by Timshel** [comment]
Hey,
So the latest lines from the log you sent me:

```
[22:14:25.254][response][INFO] (authorize) GET /identity/connect/authorize?<data..> => 307 Temporary Redirect
[22:14:25.673][request][INFO] GET /identity/connect/oidc-signin?code=...
[22:14:25.673][response][INFO] (oidcsignin) GET /identity/connect/oidc-signin?<code>&<state> => 307 Temporary Redirect
[22:14:31.987][vaultwarden::api::core::two_factor][DEBUG] Sending notifications for incomplete 2FA logins
````

So :
 - ` /identity/connect/authorize` :  the 307 will trigger the redirection to the SSO
 - `/identity/connect/oidc-signin?code`: 
   - we are coming back with a `code` so this should be a success
   - the 307 is to redirect to the application to pass the `code` and `state`

What I note is that there is no `/identity/connect/token` followup (It was present in the first screenshot).

So something happened and the redirection was not successful.

Just pushed `1.30.1-11` (~40m build) which might help in two ways : 

- correctly encode the `code` and `state` when creating the redirection url
- log the redirection url

**Comment by sandervandegeijn** [comment]
Unfortunately no luck with the -11 build, mailed the logs. Will look into it further tomorrow.

**Comment by Timshel** [comment]
Hey
The `code` in the log look strange. 
It's really big (562 chars ??) while not being a JWT token.

It appears it was even bigger for a time ???
 - https://techcommunity.microsoft.com/t5/microsoft-entra/azure-ad-b2c-authorization-code-and-refresh-token-size-increase/m-p/3770890
 
I would suggest : 
 - checking it's the same size when using web client
 - checking it's valid manually by [requesting](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#request-an-access-token-with-a-client_secret) an access token (would validate it's not mangled somewhere)
 - Trying some of the suggestion to mitigate length from the post :
     - For web applications, we recommend using OAuth2 response_mode set to form_post, to ensure the most secure transfer of tokens to your application. 
      - For single page application with authorization code flow and PKCE, reduce the number of claims omitted to your application. 
      - In the user flows, and custom policies remove claims that are unnecessary for your app. You can use the user info endpoint to return claims about the authenticated user. This will minimize the size of the authorization code and the refresh token. 
    This change should not affect device-installed apps, such as mobile and desktop apps. 
    

From what I can find of a quick search length should not be an issue but I'm unsure what else to suggest :(

**Comment by Timshel** [comment]
Another suggestion you should be able to read the log of an iphone using `idevicesyslog`  from https://docs.libimobiledevice.org/libimobiledevice/latest/.

Hum you might get nothing: https://github.com/libimobiledevice/libimobiledevice/issues/861

**Comment by sandervandegeijn** [comment]
will check on it Friday probably, we have a production deployment today and tomorrow. :)

**Comment by sandervandegeijn** [comment]
I have mailed @Timshel - we weren't able to find more details from the logs on the device itself unfortunately. But I did confirm it's still a problem on [1.30.2-3]

**Comment by derSoerrn95** [comment]
Hey, I've found the fix. The iOS app uses another path: The iOS app is doing a `GET /identity/sso/prevalidate?domainHint=vaultwarden` request instead of doing `GET /identity/account/prevalidate?domainHint=vaultwarden` request.

So a quick fix could be adding the following to the nginx config (when using a nginx reverse proxy). 
```nginx
    location ~ ^/identity/sso/prevalidate(.*)$ {
        rewrite ^/identity/sso/prevalidate(.*)$ /identity/account/prevalidate$1 permanent;
    }
```
That is going to rewrite the `sso` part of the iOS app request into `account`. 

A sustainable fix in Vaultwarden should be adding a http handler for the `sso` path.

**Comment by sandervandegeijn** [comment]
Fantastic!! Thanks! @Timshel would it be possible to add this route to the application?

**Comment by Timshel** [comment]
The Android application is doing the same call last I checked so both endpoints should be present :
 - [sso-support](https://github.com/Timshel/vaultwarden/blob/sso-support/src/api/identity.rs#L779)
 - [main](https://github.com/Timshel/vaultwarden/blob/main/src/api/identity.rs#L799)
 
@derSoerrn95   Do you have an error when calling the endpoint ?

**Comment by derSoerrn95** [comment]
> @derSoerrn95 Do you have an error when calling the endpoint ?

@Timshel which endpoint do you mean? The sso one? That returns a 404. But yes you’re right. You have to implement both. The website/browser extension are is using the account endpoint.

**Comment by Timshel** [comment]
@derSoerrn95 can you send some log and check which version of the server you are running ?

Because since the end of January both endpoint are implemented : 
 - `/identity/account/prevalidate`
 - `/identity/sso/prevalidate`

**Comment by derSoerrn95** [comment]
Oh, I see. It could be that I'm using an older version 😅 But since I'm using my nginx rewrite rule it works fine. I'm using the 'simonc/vaultwarden:latest' docker image.

**Comment by Timshel** [comment]
@derSoerrn95  the [simonc](https://hub.docker.com/r/simonc/vaultwarden/tags) images has not been updated since 2 months ago.
I'm now pushing the images to [dockerhub](https://hub.docker.com/r/oidcwarden/vaultwarden-oidc/tags), so I would recommend switching to it but test it first since there has been lots of changes ^^.

**Comment by derSoerrn95** [comment]
yeah, I was too lazy to build it myself :D

**Comment by Timshel** [comment]
@derSoerrn95 can you open a separate issue :)

**Comment by sandervandegeijn** [comment]
Switched to testing docker image: no luck :)

**Comment by Timshel** [comment]
@sandervandegeijn Hey, made no change recently that would fix the IOS issue :(

I'm not even sure which logging I could add to have more insight.

**Comment by sandervandegeijn** [comment]
Ah I thought you recreated the rewrite, sorry. If the rewrite is the solution it's a bit more difficult to implement for me (need to implement another reverse proxy on k8s.

Can I help with diagnosing this in any way?

**Comment by Timshel** [comment]
The support for both has existed for some time. 

In the log you sent me I believe it was always ok (it's called before redirecting to the SSO), the issue arises later on.

**Comment by sandervandegeijn** [comment]
Thanks. It would help a lot if we could debug the ios side, but I don't have any experience with that...

**Comment by Timshel** [comment]
I'm not sure why you are looking at the `prevalidate` call. 
From what I remember of your issue you are correctly redirected to the SSO (which happen after the `prevalidate`); and the failure happen after login on the SSO and during the redirection to the client.

Did this change ?

**Comment by sandervandegeijn** [comment]
No and I'm not looking at the call specifically, that was @derSoerrn95 . But I have identified which code breaks in the mobile app. I don't understand why because both the iOS and Android use the same code base it seems. Really weird.

**Comment by spatical** [comment]
Did a bit of testing with trying with my iPhone to log in to my vaultwarden using your latest docker image and SSO turned on and configured with Google.    SSO works great on web, but then I get the same error on iOS like is being discussed here.   

I used Charles as a proxy from my phone to log all of the URL requests/responses that occur during the SSO process.  Then I compared with the same when authenticating directly with an organization set up with SSO directly on bitwarden.com.    

The last step that does the redirect to bitwarden://sso-callback is the one step that does seem to be different.   

Comparison:  

From vaultwarden: 
bitwarden://sso-callback?code=eyJ0eXAiOiJKV1QiLCJhbGciOiJ_______gZHpugK_q7zdjBoSZByimnEE7JyWPMzpK9XiUFh03RYIGju1ogu4T_VSVUSY4OnYDxmBsVjYDyHEVYYmmrgkqD8WClD3vRhva0Y0x8MpXmvEloa_z2cfrIkg8JC2b2AMILjZGSibmr22A--nESn1L2wUKc3JxZxpYNABRE94UMpzr971axsgKRUjKGC0DMLw&state=Dntu4dyatAQLtoHFMohN7xrElg4EKgffmIvk14aFukbVRcobQ0CifNJ7lC944UPz

From bitwarden: 
bitwarden://sso-callback/?code=1A5616F52234A656384_______157FFA84798EA6BF62988EE24-1&scope=api%20offline_access&state=7WZqgetsR7Kn8liu6UQg3Reid13vREV6LAjuBVuRTtHx1TcOwnGjeedY7Dhku2G8&iss=https%3A%2F%2Fidentity.bitwarden.

I've shortened both of those since I think something in that code is probably sensitive.   But the big difference that I can see is that our vaultwarden passes a JWT as the "code" but bitwarden is just passing the code itself.    In addition, bitwarden also has additional parameters of "scope" and "iss".   

I'll see if I can provide some more details tomorrow, but in case this spurs any ideas perhaps this helps.

**Comment by Timshel** [comment]
This issue predates the switch to wrap the `code` in a JWT token, and I had wondered earlier if when too long it could cause issue but from what I could find limits are way higher. So hopefully nothing there.

Will add an `iss` parameter with the `DOMAIN` config. It does not appear to be used by the Bitwarden code, but maybe it's used in the `Xamarin` code specific to IOS.

**Comment by sandervandegeijn** [comment]
Tested it: it's working!

Great thanks guys for all the effort!

**Comment by spatical** [comment]
Thanks @Timshel!  The updated version works for me on my iPhone! I know you already closed the issue.  Just wanted to give another thank you! 🎆

**Comment by Timshel** [comment]
@spatical thanks again for the proxy logging made it easy :).
