### ISSUE TITLE
Inconsistent vault status

### ISSUE THREAD

**Issue by Halyul** [Timshel/vaultwarden#16]
### Subject of the issue

After updating to the latest `oidcwarden/vaultwarden-oidc:latest-alpine` today, I found that the web vault and the browser extension show that the vault is empty. However, iOS and Android app are able to show existing entries and sync without issues. Under this situation, I tried to create a new entry in the "empty" web vault, the new entry is synced to the browser extension (only the new entry) and the mobile apps (new entry and all existing entries). The admin interface shows that there are entries in the account, but for some reason those entires are not shown in the web vault.

Then, I reverted the database to the mainstream `vaultwarden/server:latest-alpine`, the vault returns back to normal, all entries are shown.

I'm not sure if this is an individual case.

### Deployment environment

* vaultwarden version: `oidcwarden/vaultwarden-oidc:latest-alpine`

* Install method: Docker image

* Clients used:  Web, browser extension, Android, iOS

* Reverse proxy and version:  N/A

* MySQL/MariaDB or PostgreSQL version:  postgres:16-alpine

* Other relevant details:

### Steps to reproduce

- Env:
```
DATABASE_URL
ADMIN_TOKEN
PASSWORD_HINTS_ALLOWED=false
YUBICO_CLIENT_ID
YUBICO_SECRET_KEY
EMAIL_CHANGE_ALLOWED=false
EXPERIMENTAL_CLIENT_FEATURE_FLAGS=fido2-vault-credentials,autofill-v2,autofill-overlay
PUSH_ENABLED=true
PUSH_INSTALLATION_ID
PUSH_INSTALLATION_KEY
SSO_ENABLED=true
SSO_ONLY=true
SSO_ACCEPTALL_INVITES=true
SSO_AUTHORITY
SSO_CLIENT_ID
SSO_CLIENT_SECRET
SSO_SCOPES="email profile"
SSO_FRONTEND='override'
```
- Step to reproduce: see above
- Start method: docker compose

### Expected behaviour

The web vault and the browser extension should show every entry in the vault when the vault is not empty.

### Actual behaviour

The web vault and the browser extension didn't show any entry in the vault when the vault is not empty.

### Troubleshooting data

Not sure what to capture. Will provide when requested.

**Comment by Timshel** [comment]
That's a strange one :), will try to reproduce.

Looking at the docker version it appears that [vaultwarden/server:latest-alpine](https://hub.docker.com/layers/vaultwarden/server/latest-alpine/images/sha256-0956e3932476aa120b99fd9228529133f2b45755fdcd18202069cdcaa7d5a5b2?context=explore)  is two month old could you confirm the version displayed at the bottom of the page ? (Ex latest oidc should be `2024.1.1`).

Lastly there is a `vaultwarden/server:testing-alpine` which should run a similar web-front to the oidc could you check if you have the issue with it too ? 

If the issue is still specific to the oidc version could you then try to run the oidc version without :

- `SSO_FRONTEND='override'` 
- `SSO_ONLY=true` and login using the master password

**Comment by Halyul** [comment]
The web vault version of `vaultwarden/server:latest-alpine` is `2023.10.0`; the web vault version of `vaultwarden/server:testing-alpine` is `2023.12.0`. 

When directly upgrading from `vaultwarden/server:latest-alpine` to `vaultwarden/server:testing-alpine`, the web vault shows entries normally.

When directly upgrading from `vaultwarden/server:testing-alpine` to `oidcwarden/vaultwarden-oidc:latest-alpine` without changing envs, the web vault is empty.

After commenting out `SSO_FRONTEND='override'` and `SSO_ONLY=true`, and login using the master password, the web vault shows entries. If login using SSO, the vault is empty.

**Comment by Timshel** [comment]
Look to be a tricky one.

Was not able to reproduce with:
 - wipe sqlite db
 - running VaultWarden `1.30-1` with `2023.10.0` front-end
   - Create new user
   - Add secrets / folder and notes
  - running latest oidc 
    - secrets and notes are visible
    
 But there is some good news, I'm able to reproduce if I remove the `refresh_token` .
 Can you confirm that when using `sso` the response to `identity/connect/token`  does not include a `refresh_token` ?

**Comment by Halyul** [comment]
Exactly, the response of `identity/connect/token` shows `refresh_token: null`

**Comment by Timshel** [comment]
Ok, so the web client does not like having no `refresh_token`.
Will change the logic to make something which work even without-it while still making sense.

In the mean time you probably can make your sso return a `refresh_token` by changing the requested scopes to : `SSO_SCOPES="email profile offline_access"`.

Note this might impact the session lifecycle, for example Keycloak always return a refresh_token but when using the `offline_access` the session change and cannot be invalidated anymore in the admin panel.

There might be another way to obtain a refresh_token from your sso without the offline_access scope, cf from the openid spec : 

> The use of Refresh Tokens is not exclusive to the offline_access use case. The Authorization Server MAY grant Refresh Tokens in other contexts that are beyond the scope of this specification.

Some discussion on the subject : https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1241

**Comment by Halyul** [comment]
Can confirm everything is fine after enabling refresh token on sso and adding `offline_access` to `SSO_SCOPES`
