### ISSUE TITLE
Unable to login due to invalid audience

### ISSUE THREAD

**Issue by Halyul** [Timshel/vaultwarden#28]
### Subject of the issue

After upgrading to the latest `oidcwarden/vaultwarden-oidc:latest-alpine`, the web vault prompted `Could not read id_token claims, Invalid audiences: <sso user id> is not a trusted audience` when logging in with an existing sso user in vaultwarden.

### Deployment environment

* vaultwarden version: `oidcwarden/vaultwarden-oidc:latest-alpine`

* Install method: docker

* Clients used:  web

* Reverse proxy and version:  n/a

* MySQL/MariaDB or PostgreSQL version:  `postgres:16-alpine`

* Other relevant details: 
Envs:
```
DATABASE_URL
ADMIN_TOKEN
PASSWORD_HINTS_ALLOWED
YUBICO_CLIENT_ID
YUBICO_SECRET_KEY
EMAIL_CHANGE_ALLOWED=false
EXPERIMENTAL_CLIENT_FEATURE_FLAGS=fido2-vault-credentials,autofill-v2,autofill-overlay
PUSH_ENABLED=true
PUSH_INSTALLATION_ID
PUSH_INSTALLATION_KEY
SSO_ENABLED=true
SSO_ONLY=true
SSO_ACCEPTALL_INVITES=true
SSO_AUTHORITY
SSO_CLIENT_ID
SSO_CLIENT_SECRET
SSO_SCOPES="email profile offline_access"
SSO_FRONTEND='override'
LOG_LEVEL=debug
```

### Steps to reproduce

Registering a sso user in an older version of `oidcwarden/vaultwarden-oidc` and then upgrading to the latest version of `oidcwarden/vaultwarden-oidc`. After that, logging in this user using sso in the web vault.

### Expected behaviour

The user is able to log in.

### Actual behaviour

The user is unable to log in with an error `Could not read id_token claims, Invalid audiences: <sso user id> is not a trusted audience`

### Troubleshooting data

Will be provided as requested.

**Comment by Timshel** [comment]
Can you remind me which SSO you are using ?

**Comment by Halyul** [comment]
[zitadel](https://github.com/zitadel/zitadel)

**Comment by Timshel** [comment]
Hey,

So it appears that it send multiple audience including `<sso user id>` ?
You can check it by setting : 
```
LOG_LEVEL=debug
SSO_DEBUG_TOKENS=true
```
And you can decode the jwt using https://jwt.io for ex.

The code mention that the spec is quite strict : https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

> The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience. The aud (audience) Claim MAY contain an array with more than one element. The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client. 

Any way to remove the additional audience in Zitadel ?

**Comment by Timshel** [comment]
So the lib support adding additional trusted `audience`.

The best would probably to add a config with the possible additional audience. 
Reading [this](https://stackoverflow.com/questions/76217815/protecting-an-axum-app-with-openid-and-zitadel) it appears that the second id should be the Zitadel resource ID of your project  ?

If it´s the case then it's stable enough to add to the conf. If it's a ` <sso user id>` as you mention then it won't be possible and it would mean that something like trusting all audience would be needed :(.

**Comment by Halyul** [comment]
Indeed Zitadel includes `project id` and `client id` in `aud`. `project id` can be removed with extra coding snippets, but adding additional trusted audience is much simpler. Is there a way I can do that?

**Comment by Timshel** [comment]
Added the `SSO_AUDIENCE_TRUSTED` config to allow to pass a regex to trust additional audience (use single quote: `'^$'` )

Will be available in `1.30.2-6` when it finished building in 1h :).

**Comment by Halyul** [comment]
can confirm the issue is fixed

**Comment by Timshel** [comment]
Will add a mention is the SSO doc.
I guess you had to add the `offline_access` scope to obtain a `refresh_token` ?

**Comment by Halyul** [comment]
correct

**Comment by Halyul** [comment]
I encounter a new issue now. When I restart the `vaultwarden` container, I can login normally. However, after several hours (for me, ~12 hours), when I try to login with sso, the web vault prompts `Could not read id_token claims, Signature verification failed`. 

I have now enabled debugging logging and restarted the container, thus the issue is gone. Will try to provide logs after ~12 hours when I encounter the same issue.

**Comment by Timshel** [comment]
Hey,
I expect it's due to the fact that I used a cache for the OpenId client.
Searching on the underlying  library it's in fact not recommended.: https://github.com/ramosbugs/openidconnect-rs/issues/25

I'm curious, can you check the `cache-control` header returned when calling the discovery endpoint `.../.well-known/openid-configuration` ?

On Keycloak and Gitlab it return no cache and Google return `max-age=3600`.

**Comment by Halyul** [comment]
`Cache-Control: no-store`

**Comment by Halyul** [comment]
Actually, there is another issue where the refresh token isn't working. The log says
```
[2024-02-18 09:08:22.878][vaultwarden::sso][ERROR] Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: invalid_request, error_description: Some("Errors.User.RefreshToken.Invalid"), error_uri: None })
[2024-02-18 09:08:22.878][vaultwarden::api::identity][ERROR] {"ErrorModel":{"Message":"Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: invalid_request, error_description: Some(\"Errors.User.RefreshToken.Invalid\"), error_uri: None })","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: invalid_request, error_description: Some(\"Errors.User.RefreshToken.Invalid\"), error_uri: None })","Object":"error","ValidationErrors":{"":["Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: invalid_request, error_description: Some(\"Errors.User.RefreshToken.Invalid\"), error_uri: None })"]},"error":"","error_description":""}
...
[2024-02-18 09:08:23.231][vaultwarden::sso][ERROR] Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: invalid_request, error_description: Some("Errors.User.RefreshToken.Invalid"), error_uri: None })
...
```
Not sure where to start debugging.

**Comment by Timshel** [comment]
I expect that the `Errors.User.RefreshToken.Invalid` is sent back by your SSO.

**Comment by Halyul** [comment]
can confirm the caching issue is gone.

For the refresh token issue, the latest log shows 
```
[2024-02-20 03:28:06.127][vaultwarden::auth][ERROR] Invalid refresh token
[2024-02-20 03:28:06.127][vaultwarden::api::identity][ERROR] {"ErrorModel":{"Message":"Invalid refresh token","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Invalid refresh token","Object":"error","ValidationErrors":{"":["Invalid refresh token"]},"error":"","error_description":""}
```
Not sure it is a sso issue or vaultwarden issue.

**Comment by Timshel** [comment]
With the PR VaultWarden generate it's own `refresh_token` and `access_token`.
But the generated `access_token` expiration is taken from your sso `access_token` that's why you can check expiration with the values returned by the token endpoint.

Alternatively you can activate `SSO_DEBUG_TOKENS=true` and directly check the tokens returned by your sso.

**Comment by Halyul** [comment]
I can see the lifetime of `access token` is set to 12 hours, which matches the client gets logged out after 12 hours behaviour.

**Comment by Timshel** [comment]
Not sure what else could trigger the `Invalid refresh token`.

I would start by lowering the `access_token` lifetime to like 10min to ease debugging,
Additionally you can force a refresh token call by creating a new Organization.

**Comment by Halyul** [comment]
Still cannot find any more details regarding this. I will close this issue for now, once I find more, I will submit a new issue

**Comment by LeVraiRoiDHyrule** [comment]
> I encounter a new issue now. When I restart the `vaultwarden` container, I can login normally. However, after several hours (for me, ~12 hours), when I try to login with sso, the web vault prompts `Could not read id_token claims, Signature verification failed`.
> 
> I have now enabled debugging logging and restarted the container, thus the issue is gone. Will try to provide logs after ~12 hours when I encounter it again.

Hi, I am having a similar issue, but without any more issue than the "Signature verification failed". Here are my logs:
https://privatebin.net/?712bf67680818e54#5Togiex9tjFFqN1KpL4iM7qvpx1Q5VUaJrG7pHi7njDR

I looked at `https://myopenidprovider.com/.well-known/openid-configuration` and I find no `cache-control` setting.

Would you have an idea of what could be wrong ?
Thanks in advance for any answer and have a nice day
