### ISSUE TITLE
Issues with asking for 2fa after SSO if user previously enabled 2fa

### ISSUE THREAD

**Issue by LightningManGTS** [Timshel/vaultwarden#3]
Good Afternoon,

I have your branch deployed and am testing it with DUO. Right now I am stuck with the following error in console when looking at the page in developer mode
![image](https://github.com/Timshel/vaultwarden/assets/3919521/208a8704-6409-48a3-871d-d6910e52785c)

I'm assuming there is an issue with my Attribute mappings since it says the token doesn't contain an email.
![image](https://github.com/Timshel/vaultwarden/assets/3919521/f2eea617-61bf-4c0a-ae57-d71faea0f0d2)

I pulled this branch about 2 hours ago. 

On that note I can get more in depth information regarding the environment later. For now know that I deployed this to an LXC using TTeck's script and replacing the github repo's with yours instead of the main branch. Everything shows up fine and Vaultwarden is stable otherwise so I'm fairly certain this is more to do with Attribute mapping then anything else. I looked to see where you may have had the attributes posted but I did not see where.

**Comment by LightningManGTS** [comment]
Never mind, I figured it out. (mail and email address are the same in my enviroment but thats fine)
 ![image](https://github.com/Timshel/vaultwarden/assets/3919521/db0197c2-f00d-4e0e-ad0e-4184328506df)

The only other thing of note is that signing in with SSO is then taking me through the normal 2fa step through, as you can probably imagine, DUO 

![image](https://github.com/Timshel/vaultwarden/assets/3919521/1608bcfe-cf26-45d3-833e-027292536698)

**Comment by Timshel** [comment]
Hey,
I tested some 2FA with SSO activated but not all solutions.
Just had a look at DUO and even the free trial creation is asking for a phone number so won't be able to test it.

Can you clarify the issue with DUO 2FA ? do you have the server side error when it fails ?

**Comment by LightningManGTS** [comment]
It appears that after SSO and when it goes to access the traditional prompt iframe it errors. Likely some information not being transmitted from the authentication attempt when ussing SSO compared to logging in normally. That information could be related to the master password step since in SSO it asks for the master password after the 2fa step and not before it like a normal login (and may not be decrypting the data necessary to complete DUO? this last bit is spit balling). 

![image](https://github.com/Timshel/vaultwarden/assets/3919521/ffa6dba9-c4b3-4257-be7d-233b62ddd67b)

**Comment by Timshel** [comment]
Hey,
Managed to setup a DUO account to test it using an android device and the duo mobile app.
After an SSO login the 2FA prompt is triggered but validation fail, while it works when using only Master password.
Will try to fix it :)

**Comment by Timshel** [comment]
Just pushed a fix for the DUO 2fa it was relaying on an optional field to find the user email.

But I'm unsure if you didn't have a different issue, still can you test with latest ?

**Comment by LightningManGTS** [comment]
Getting the same thing, but its at least attempting to go through 2fa first. TI tested both with and without remembered devices
![image](https://github.com/Timshel/vaultwarden/assets/3919521/6f4366e1-86f9-444d-be84-43aee4820bd9)
![image](https://github.com/Timshel/vaultwarden/assets/3919521/1c4adf23-8d63-469a-9a04-66e5a226d9cb)

I update at 12:30pm my time so it should have pulled the latest changes

![image](https://github.com/Timshel/vaultwarden/assets/3919521/6752b815-773f-4868-945a-9de1af004329)

**Comment by LightningManGTS** [comment]
Good news!

I updated my instance just now and tried the traditional duo 2 factor prompt when going through SSO and it is now working. It test both with and without Remembered Devices policy being enabled. I do believe this is resolved.
