### ISSUE TITLE
Extension not syncing - web vault working fine

### ISSUE THREAD

**Issue by whallin** [Timshel/vaultwarden#30]
I'm currently testing the build `1.30.2-6` with authentik as the identity provider on a fresh install. I've got all SSO options configured successfully via the environmental variables and the /admin endpoint (for the sake of testing).

Authentication works as expected. I can sign up and sign in using my authentik instance—no questions asked. However, the web vault is the only thing that is actually in sync.

Any changes made via the web vault **do not** show up when signed in to the browser extension (at least on Chromium-based browsers). However, if the change is made **via the browser extension**, the changes do show up in the web vault. Once present in the web vault, any changes there will sync to the browser extension.

Trying to "Sync vault now" via the browser extension settings ends up in an infinite loading with no console output with `LOG_LEVEL` set to `DEBUG`.

I've gone ahead and attached the debug logs from when I authenticated through the browser extension.

[vaultwarden-console-browser-ext-auth-logs.txt](https://github.com/Timshel/vaultwarden/files/14315070/vaultwarden-console-browser-ext-auth-logs.txt)

**EDIT 1:** Clarification on "change"; let's say I create an item via the browser extension. That shows in the web vault, and can also be deleted from there. The deletion will sync over to the browser extension—no problem. The other way around, however, does **not** work for me.

**EDIT 2:** Felt the need to try it out on the official Bitwarden app for iOS. The issue is not present there, works just as expected. No troubles with authentication via SSO either.

**Comment by Timshel** [comment]
Hey,
Had a similar bug (in the web) when I made a change which resulted in returning no `refresh_token` but should never happen now.
Will try to reproduce.

**Comment by whallin** [comment]
@Timshel I've gone ahead and attached my Docker stack for troubleshooting. The SSO settings are currently set via the /admin endpoint.

**Comment by whallin** [comment]
**Update:** I wiped the data and recreated the Vaultwarden instance. It seems to work now. However, I'll try to continue reproducing as I'm quite clueless.

**Comment by whallin** [comment]
I've sadly yet been able to recreate the issue. I'm gonna go ahead and close this. If someone experiences something similar, feel free to reopen this.
