### ISSUE TITLE
Session Timeout when using the latest image (1.30.3-2)

### ISSUE THREAD

**Issue by derSoerrn95** [Timshel/vaultwarden#34]
### Subject of the issue
Session Timeout when using the latest image (1.30.3-2)

### Deployment environment

* vaultwarden version: 1.30.3-2

* Install method: docker, oidcwarden/vaultwarden-oidc:1.30.3-2

* Clients used: 
   * web vault (firefox)
   * desktop (Windows, MacOS, Linux)
   * iOS

* Reverse proxy and version: nginx/1.18.0

* MySQL/MariaDB or PostgreSQL version: no db server

* Other relevant details:

### Expected behaviour
able to sign in with sso oidc (authentik)

### Actual behaviour
Session timeout error

### Troubleshooting data
Ok, too bad. When using your latest image I'm getting a session timeout error.

```bash
vaultwarden-server-1  | [2024-02-23 19:12:29.306][request][INFO] GET /icons/sso_host/icon.png
vaultwarden-server-1  | [2024-02-23 19:12:29.314][response][INFO] (icon_internal) GET /icons/<domain>/icon.png => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:32.478][request][INFO] GET /notifications/hub?access_token=XXX
vaultwarden-server-1  | [2024-02-23 19:12:32.480][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from x.x.x.x
vaultwarden-server-1  | [2024-02-23 19:12:32.485][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:35.524][request][INFO] GET /identity/connect/oidc-signin?code=xxx
vaultwarden-server-1  | [2024-02-23 19:12:35.528][response][INFO] (oidcsignin) GET /identity/connect/oidc-signin?<code>&<state> => 307 Temporary Redirect
vaultwarden-server-1  | [2024-02-23 19:12:36.269][request][INFO] GET /api/config
vaultwarden-server-1  | [2024-02-23 19:12:36.269][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-02-23 19:12:36.269][response][INFO] (config) GET /api/config => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:37.197][vaultwarden::api::identity][INFO] User xx@example.com logged in successfully. IP: x.x.x.x
vaultwarden-server-1  | [2024-02-23 19:12:37.197][response][INFO] (login) POST /identity/connect/token => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:37.270][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-02-23 19:12:38.215][response][INFO] (login) POST /identity/connect/token => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:38.312][request][INFO] GET /api/config
vaultwarden-server-1  | [2024-02-23 19:12:38.312][response][INFO] (config) GET /api/config => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:40.668][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-02-23 19:12:41.625][response][INFO] (login) POST /identity/connect/token => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:41.687][request][INFO] POST /api/accounts/verify-password
vaultwarden-server-1  | [2024-02-23 19:12:41.797][response][INFO] (verify_password) POST /api/accounts/verify-password => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:41.881][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-02-23 19:12:41.882][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-02-23 19:12:41.884][vaultwarden::auth][ERROR] Invalid refresh token
vaultwarden-server-1  | [2024-02-23 19:12:41.884][vaultwarden::api::identity][ERROR] {"ErrorModel":{"Message":"Access token is close to expiration but we have no refresh token","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Access token is close to expiration but we have no refresh token","Object":"error","ValidationErrors":{"":["Access token is close to expiration but we have no refresh token"]},"error":"","error_description":""}
vaultwarden-server-1  | [2024-02-23 19:12:41.884][response][INFO] (login) POST /identity/connect/token => 401 Unauthorized
vaultwarden-server-1  | [2024-02-23 19:12:41.951][request][INFO] GET /api/config
vaultwarden-server-1  | [2024-02-23 19:12:41.951][response][INFO] (config) GET /api/config => 200 OK
vaultwarden-server-1  | [2024-02-23 19:12:42.824][response][INFO] (login) POST /identity/connect/token => 200 OK
```

As you can see in the log I'm able to authenticate with my sso provider (authentik). Then I have to pass my master password but after that I'm getting a 401 and the error for an invalid refresh token.

**Comment by derSoerrn95** [comment]
oh, i saw the log message to increase the access token lifetime to more than 5 min... 🤦🏻‍♂️

**Comment by derSoerrn95** [comment]
Hm, I think I have to reopen this issue. When using Authentik as you described in your example folder I'm not able to get a refresh token. There's always the error message like in the log above: 

```
vaultwarden-server-1  | [2024-03-02 14:42:58.898][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-03-02 14:42:58.899][vaultwarden::auth][ERROR] Token has expired
vaultwarden-server-1  | [2024-03-02 14:42:58.899][vaultwarden::auth][ERROR] Impossible to read refresh_token: {"ErrorModel":{"Message":"Token has expired","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Token has expired","Object":"error","ValidationErrors":{"":["Token has expired"]},"error":"","error_description":""}
vaultwarden-server-1  | [2024-03-02 14:42:58.899][vaultwarden::api::identity][ERROR] {"ErrorModel":{"Message":"Impossible to read refresh_token: {\"ErrorModel\":{\"Message\":\"Token has expired\",\"Object\":\"error\"},\"ExceptionMessage\":null,\"ExceptionStackTrace\":null,\"InnerExceptionMessage\":null,\"Message\":\"Token has expired\",\"Object\":\"error\",\"ValidationErrors\":{\"\":[\"Token has expired\"]},\"error\":\"\",\"error_description\":\"\"}","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Impossible to read refresh_token: {\"ErrorModel\":{\"Message\":\"Token has expired\",\"Object\":\"error\"},\"ExceptionMessage\":null,\"ExceptionStackTrace\":null,\"InnerExceptionMessage\":null,\"Message\":\"Token has expired\",\"Object\":\"error\",\"ValidationErrors\":{\"\":[\"Token has expired\"]},\"error\":\"\",\"error_description\":\"\"}","Object":"error","ValidationErrors":{"":["Impossible to read refresh_token: {\"ErrorModel\":{\"Message\":\"Token has expired\",\"Object\":\"error\"},\"ExceptionMessage\":null,\"ExceptionStackTrace\":null,\"InnerExceptionMessage\":null,\"Message\":\"Token has expired\",\"Object\":\"error\",\"ValidationErrors\":{\"\":[\"Token has expired\"]},\"error\":\"\",\"error_description\":\"\"}"]},"error":"","error_description":""}
vaultwarden-server-1  | [2024-03-02 14:42:58.899][response][INFO] (login) POST /identity/connect/token => 401 Unauthorized
vaultwarden-server-1  | [2024-03-02 14:42:59.006][request][INFO] GET /api/config
```

**Comment by Timshel** [comment]
Hey
Can you remind me where to change the access token expiration ? I can't manage to find it anymore :(.

**Comment by Timshel** [comment]
Hey

Can you give me more details on what's happening ?

When testing on my side, since Authentik do not return a JWT `refresh_token` the expiration of the generated VW `refresh_token` is set to 7 days (can check this using jwt.io). So it means the error you see  (`Token has expired`) should appear only after 7 days of idle time (it's extended with activity). 

I tested the access token refresh by creating a new Organization which force the refresh, and it had no issues.

**Comment by derSoerrn95** [comment]
Hi, 
I tried @Node815's suggestion to stop my Docker service, run `docker system prune` and restart the Vaultwarden service, but that doesn't change the behavior. I lose my session after 15 minutes (which is the validity period of my Authentik access token). 

Where can I find the access token generated by VW when using the browser extension?  When I log in to the web view (using Chrome) and look under Application --> Local Storage --> [a uuid] --> Token, I see a `refreshToken` and an `accessToken` - both have the same expiry time. This also seems to be 15 minutes, like the lifetime of my authentication access token.

I have also added the `offline_access` section in my Vaultwarden Authentik provider as it is required for refresh tokens from 
Authentik 2024.2 onwards (see https://docs.goauthentik.io/docs/providers/oauth2/#refresh_token).

To reproduce the error, I have to log in to Vaultwarden with sso (Authentik). Then I can use it for 15min. After that I have to log in again with Authentik because the access token has expired and a refresh token was not found.

**Comment by Timshel** [comment]
If you are running Firefox you can go to `about:debugging#/runtime/this-firefox` And inspect an extension (Maybe there is something equivalent on chrome no idea). 
Otherwise, can you just test outside the extension in a web session, the endpoint used to refresh the tokens is `/identity/connect/token`.
If you want for it to go faster set the expiration to 6 min this way you have only 1min before VaultWarden consider your session as expired.

And on the server side you can run with :
```
SSO_DEBUG_TOKENS=true
LOG_LEVEL_OVERRIDE="
vaultwarden::api::identity=debug
vaultwarden::auth=debug
vaultwarden::sso=debug
"
```

**Comment by derSoerrn95** [comment]
Here is the debug log when signing in:

```
[2024-03-06 13:26:24.136][vaultwarden::sso][DEBUG] Refresh token: None
vaultwarden-server-1  | [2024-03-06 13:26:24.136][vaultwarden::sso][DEBUG] Expiration time: Some(900s)
vaultwarden-server-1  | [2024-03-06 13:26:24.138][vaultwarden::sso][DEBUG] No refresh_token present
vaultwarden-server-1  | [2024-03-06 13:26:24.140][vaultwarden::api::identity][INFO] User user@example.com logged in successfully. IP: 104.151.30.194
vaultwarden-server-1  | [2024-03-06 13:26:24.140][response][INFO] (login) POST /identity/connect/token => 200 OK
vaultwarden-server-1  | [2024-03-06 13:26:24.283][request][INFO] GET /api/config
vaultwarden-server-1  | [2024-03-06 13:26:24.283][response][INFO] (config) GET /api/config => 200 OK
vaultwarden-server-1  | [2024-03-06 13:26:24.284][request][INFO] POST /identity/connect/token
vaultwarden-server-1  | [2024-03-06 13:26:24.880][vaultwarden::sso][DEBUG] No refresh_token present
vaultwarden-server-1  | [2024-03-06 13:26:24.882][response][INFO] (login) POST /identity/connect/token => 200 OK
vaultwarden-server-1  | [2024-03-06 13:26:24.910][request][INFO] GET /api/sync
vaultwarden-server-1  | [2024-03-06 13:26:24.942][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
```

**Comment by Node815** [comment]
It seems your connection is fine based on your above log- out of curiosity what is your setting like here and in the extension's settings?  Since you said it's 15 minutes, I think that's the default for VW? I have mine set to never as I'm the only one on my machine most of the time.  But that's just me:

![image](https://github.com/Timshel/vaultwarden/assets/20736534/95f51c21-98b9-4535-adca-6966d9077e94)

Whereas my Authentik (V 2024.2.2) is at default for the timeouts, and I have yet to see it kick me out. 

![image](https://github.com/Timshel/vaultwarden/assets/20736534/740b4dd6-cd0b-4a05-8d12-07ba7c775ac2)
When I mentioned my issue - it was immediately after successful authentication via Authentik.  So I never got a chance to set my master password for the vault after logging in with a known user in my Authentik system.

**Comment by derSoerrn95** [comment]
I'm using the following settings:

Webview:
![https://imgur.com/P0nHAey.png](https://imgur.com/P0nHAey.png)

Extension:
![https://imgur.com/jOXkE4g.png](https://imgur.com/jOXkE4g.png)
(excuse the language - my work browser is set to german)

But as you can see none of the VW settings is set to `log out`. Both are set to `lock`, which should only lead to unlock my vault by master password.

Authentik:
![https://i.imgur.com/2tTlcq9.png](https://imgur.com/2tTlcq9.png)

As I mentioned ealier I also added the `offline_access` scope.

**Comment by Timshel** [comment]
@derSoerrn95 from the log : 

```
[vaultwarden::sso][DEBUG] No refresh_token present
```
So Authentik is not sending you the refresh token.
Trying to update the image to test.

**Comment by Timshel** [comment]
Looking at the doc you are missing some configuration.
You need to look at the `authorization_code` which give youn initially the `refresh_token` : https://docs.goauthentik.io/docs/providers/oauth2/#authorization_code

It mention : 
> In authentik this can be done by selecting the offline_access Scope mapping in the provider settings.

**Comment by Timshel** [comment]
@derSoerrn95 ok looking back at your screenshot you are correctly activating the offline scope in Authentik.
But as I mention I believe you have issue when setting the scope since it's working on my side with the scope selected in Authentik.
with: 
```
SSO_SCOPES="email profile offline_access"
```

**Comment by Timshel** [comment]
If you ever change setting using the admin console you might have some override in `data/config.json`.
It should tell you if it's loading something at the start of the server.

**Comment by derSoerrn95** [comment]
omg, damn didn't know that it is possible to set the scopes. I'm sorry.
But I think it works now. Thanks for your help :)

I'm getting the following log;

```
vaultwarden-server-1  | [2024-03-06 15:49:42.169][vaultwarden::sso][DEBUG] Refresh token: Some("R3***GA")
vaultwarden-server-1  | [2024-03-06 15:49:42.169][vaultwarden::sso][DEBUG] Expiration time: Some(900s)
vaultwarden-server-1  | [2024-03-06 15:49:42.173][vaultwarden::sso][DEBUG] Non jwt refresh_token (expiration set to 1710341382)
```

**Comment by Timshel** [comment]
Yes in the provider you are setting the scopes the application is allowed to request, but you still need to request them ^^.
I'm updating the doc to add the `2024.2` change.

**Comment by derSoerrn95** [comment]
I can also do a PR later if you want
