### ISSUE TITLE
SSO enabled - Masterpassword still requested

### ISSUE THREAD

**Issue by Estradamis** [Timshel/vaultwarden#38]
Hey all,

today I deployed the SSO enabled Vaultwarden to try it out. When using SSO, it first asks for userID which is fine and creates the account - but then it asks for a master password as well as with each login, the MasterPassword is required (I hoped that this can be avoided with SSO, correct me if I'm wrong?). 

In the admin config, I have checked Disable Email+Master Password login

**Comment by Estradamis** [comment]
nvm - I should read the comments provided in the vaultwarden discussion. Sorry :)

**Comment by arabezar** [comment]
Hi @Estradamis,
And what was the issue?
I have the same behavior, still cannot figure it out :(
I'll appreciate if you could provide a link to that discussion please

**Comment by Estradamis** [comment]
> Hi @Estradamis, And what was the issue? I have the same behavior, still cannot figure it out :( I'll appreciate if you could provide a link to that discussion please

@arabezar there is no issue, this is intended behavior and described in the discussion, so you cannot get around it
