### ISSUE TITLE
Can not add new user to organization 

### ISSUE THREAD

**Issue by AlexShku** [Timshel/vaultwarden#4]
Hello! 
I encountered a problem with your build: after an invitation to the Organization is sent to a new user and he accepts and logs in, his status does not change and he remains in the **Invited** status.
I did several different tests and still the same.

![image](https://github.com/Timshel/vaultwarden/assets/91185761/4be63963-2cf6-4877-bfb8-b252b420bde6)

Is anyone facing the same problem?

**Comment by Timshel** [comment]
I believe you are describing the issue mentioned in the PR, possible solutions are mentioned there.

**Comment by AlexShku** [comment]
I see. Thanks!

**Comment by Timshel** [comment]
If it resolve your issues can you close this ? :)

**Comment by AlexShku** [comment]
I'm not sure about issue resolving. Did it fixed in new version?

**Comment by Timshel** [comment]
Did you test the possible solutions mentioned in the issue ?
