### ISSUE TITLE
Problem with chrome extension

### ISSUE THREAD

**Issue by Himlol** [Timshel/vaultwarden#5]
### Subject of the issue

Hello,

I just tested sso with using the [docker-compose](https://github.com/Timshel/vaultwarden/blob/main/test/oidc/docker-compose.yml) file provided.
And I discovered that the chrome-browser extension "Bitwarden" doesn't working. 
When you clicking on “Enterprise single sign-on” apparently incorrectly sent a request like this for the vaultwarden server.
It looks like `http://127.0.0.1:8000/vault/#/sso?clientId=browser&redirectUri=http%3A%2F%2F127.0.0.1%3A8000%2Fvault%2Fsso-connector.html&state=qHeuRkYKafKYvPRBWe5ucp7fFcCp4q6NKqeaCRzpfJDc7jkxtakxgT97ZXsET5Ea:clientId=browser&codeChallenge=3r-NQA4CQyCPBrx5mhXlOAqUI0E6OWwAlJGNcK83WU8&email=test%40yopmail.com` and return 404 HTTP response.

Perhaps I'm doing something wrong, but if not, are there plans to support SSO when working with the browser extension?
### Deployment environment
All environment from [test directory](https://github.com/Timshel/vaultwarden/tree/main/test/oidc) without changes.

**Comment by Timshel** [comment]
Hey,
Thanks for the issue, was a bit busy at the moment so can't look at it for now.
Should have some time at the start of next week.

**Comment by Timshel** [comment]
Hey,

Just tested in Chromium and set the Server url to `http://127.0.0.1:8000` for the extension config and had no issue.

Can you confirm that the login is working outside of the extension ? 

When running the `docker-compose` with the `--build VaultWarden` it appears that sometimes the script creating the realm on Keycloak is not run (no idea why) this could explain the 404 you are seeing. If it's the case just running the compose without the build again should make it work.

**Comment by Himlol** [comment]
Hello,

Yes, you are right, the problem was in `--build VaultWarden` option. I also tested authentik way and it works great.
Thank you for help.

Now I will try to connect vw-sso with authelia. I'll come back with docker-compose example for your test collection.
