### ISSUE TITLE
Error 502 using Azure AD

### ISSUE THREAD

**Issue by SilvaFernando** [Timshel/vaultwarden#51]
HI.
I'm testind vaultwarden using this image timshel/vaultwarden:1.30.5-9 and Azure Oauth using this documentation:https://github.com/Timshel/vaultwarden/blob/sso-support/SSO.md#microsoft-entra-id
![image](https://github.com/Timshel/vaultwarden/assets/53239752/a1b59338-4820-489a-b1ec-0223b923bc77)

![image](https://github.com/Timshel/vaultwarden/assets/53239752/893fbe65-e972-4afd-bd0a-399cdd532f67)

SSO_ENABLED=true
SSO_CLIENT_ID={client_id}
SSO_CLIENT_SECRET={client_secret}
SSO_AUTHORITY=https://login.microsoftonline.com/{tenant_id}/v2.0

**Comment by Timshel** [comment]
Do you have the 502 when coming back to Vaultwarden after login on Azure AD ?
Any error in the server logs ?

**Comment by SilvaFernando** [comment]
After Azure AD logon:
![image](https://github.com/Timshel/vaultwarden/assets/53239752/712cff5e-874f-45b7-ae1e-ccda557cabe3)

**Comment by Timshel** [comment]
From the logs the redirection from Azure appear to be working but then Vaultwarden need to redirect to itself, and it fails (unless you did not include any follow-up logs).

So I would say:
 - Open the network panel in your browser debugger and check the cause for the redirection failure.
 - Check your `DOMAIN` config it's used to build the url logged in `Redirection to`, is it truly valid ? no typo ?
 - Check your proxy settings is it blocking the redirection ?
 
 Remarks on your anonymization of the logs :
  - The domain is probably still legible ;).
  - The `code` included is the redirection is sensitive information but should have a short life .

**Comment by SilvaFernando** [comment]
On Azure side I'm using something like that:
![image](https://github.com/Timshel/vaultwarden/assets/53239752/fbca50a7-c8cf-40d3-aa3b-29e19e6457eb)

On Vaultwarden side, I'm using a Nginx Proxy Manager with this options:
![image](https://github.com/Timshel/vaultwarden/assets/53239752/b7be7b06-ee1f-46c0-a0bf-08b90ab65a8c)

And my envs:
![image](https://github.com/Timshel/vaultwarden/assets/53239752/6d774780-8bb3-414d-8660-2977f145a727)
![image](https://github.com/Timshel/vaultwarden/assets/53239752/43d0d576-4e77-4503-913c-66c7df45c99f)

If I'm doing something wrong please, let me know

**Comment by Timshel** [comment]
Hey
Have you checked what I mentioned in my previous comment ?
I would say try to manually redirect to redirection uri mentioned in the log.

**Comment by SilvaFernando** [comment]
Yes the redirect URI is valid, I've tried copy and access on my browser.

One thing when I tried https://my-dns/identity/connect/oidc-signin I have this error:
![image](https://github.com/Timshel/vaultwarden/assets/53239752/74218940-4d9b-4670-995a-86950051c21f)

**Comment by Timshel** [comment]
Yes, without the query parameters rocket return a 404, il you add a dummy `code` and `state` you'll get a 400 failure.

In your server log the 307 redirection was correctly generated so no issue here. 

I have no idea why the url would work manually but the browser would fail to redirect. 
Maybe check the browser debugger to see if there is more information ?

**Comment by Timshel** [comment]
Are you by chance running on  Synology ? 
There is some discussion on reddit [eng](https://old.reddit.com/r/nginxproxymanager/comments/13mpzyp/502_bad_gatewayopenresty_nginx_fault/) and [fr](https://www.reddit.com/r/nginxproxymanager/comments/13mpzyp/502_bad_gatewayopenresty_la_faute_de_nginx/fr/)
