### ISSUE TITLE
SSO Open ID Configuration issue with authelia

### ISSUE THREAD

**Issue by Daniel-dev22** [Timshel/vaultwarden#56]
Is it possible to simply provide the full open id Configuration url and not have it automatically try to add the /api/oidc/authorization/.well-known/openid-configuration to the SSO_AUTHORITY
"https://authelia.domain.net/.well-known/openid-configuration" is what works with latest version of authelia.

**Comment by Timshel** [comment]
No,

The path appended is `/.well-known/openid-configuration`, it's done by the `openidconnect` library.
It's hardcoded because it's defined in the spec: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

In your case setting `SSO_AUTHORITY=https://authelia.domain.net` should work.

**Comment by Timshel** [comment]
> `http://authelia.oidc.domain.net` expected `https://authelia.oidc.domain.net`

You have a mismatch configuration of `http` and `https`.

**Comment by Timshel** [comment]
I was editing my comment :D.

Reading your comment again it probably means you need to make Authelia aware that it's behind a proxy handling `https` for it to report its url with `https`.

**Comment by Timshel** [comment]
Yes, if I'm not mistaken Argon is a hash function but we need to be able to send the secret to the SSO provider.

**Comment by Timshel** [comment]
> It wouldn't be possible to unhash it to get the value

That's kind of what hash function are made to prevent.

For the admin token what is done is that the password you input is hashed, and the resulting hash is compared with the one from the config.

**Comment by Timshel** [comment]
An identifier is built using `{iss}/{sub}` (`iss` usually provider url, `sub` provider identifier).

- did you change the SSO url ?
- did you wipe you SSO database and tried to login again ?

**Comment by Timshel** [comment]
If by SSO database you mean the database for Authelia then no, it would not fix your issue.

But since the provider url changed from the point of view of Vaultwarden you have to remove the association.
A simple truncate in Vaultwarden database should do the job:
```sql
TRUNCATE TABLE sso_users;
```

**Comment by Timshel** [comment]
If you are asking I'm guessing you are using sqlite, by default the database is at `data/db.sqlite3` relative to the vaultwarden executable. You'll have to read it using a client to run sql command against it.

**Comment by Timshel** [comment]
Would have to see with more feedback but for now I see it more as a feature than a bug.

**Comment by Timshel** [comment]
> [vaultwarden::auth][ERROR] Token has expired

Maybe too short of a Refresh Token expiration ? If you have an idle expiration it needs to be sufficient to allow for it to be still valid after the access token expiration.
