### ISSUE TITLE
podman-compose produces Bad Request

### ISSUE THREAD

**Issue by jobritz** [Timshel/vaultwarden#57]
Hi, just encountered a strange issue. I tried to setup vaultwarden with SSO with podman-compose and at first sight everything looks fine.
But when I try to login with SSO I get a Bad Request (400) error and SSO isn't working therefore.
Running vaultwarden with podman the standard way does however work perfectly fine.

**podman-compose file:**

services:
  vaultwarden:
    image: timshel/vaultwarden:1.30.5-9
	container_name: vaultwarden
	restart: always
	ports:
	  - 8000:80
	env_file:
	  - vault.env
	volumes: /vw-data:/data

**podman command:**

podman run -d --name vaultwarden -p 8000:80 --env-file=vault.env -v /vw-data/:/data/ --restart=always timshel/vaultwarden:1.30.5-9

I'm new to podman-compose so I think there could be my issue, but maybe you do have a tip or a hint for me?

**Comment by Timshel** [comment]
Hey
Sorry I have no experience with `podman`.
