### ISSUE TITLE
SSO Button missing

### ISSUE THREAD

**Issue by maxulm** [Timshel/vaultwarden#6]
### Deployment environment

* vaultwarden version:

* Install method:

* Clients used: web vault

* Reverse proxy and version: nginx

* MySQL/MariaDB or PostgreSQL version: PostgreSQL

* Other relevant details:

### Steps to reproduce
Opening root url
### Expected behaviour
Seeing an SSO-button

### Actual behaviour
Just mail login is provided

### Troubleshooting data
![image](https://github.com/Timshel/vaultwarden/assets/19280402/66dfedc9-9923-4e75-b90a-4f723ec08da5)

**Comment by Timshel** [comment]
Hey,

With the default front-ent version the SSO login button is only visible after you enter an email address.
[VaultWarden](https://github.com/dani-garcia/vaultwarden) maintainer are not keen on patching the front-end so this logic can't be changed.

I made a patched version of the front-end to remove this step available here : https://github.com/Timshel/oidc_web_builds
But don't expect it to merged in the official VaultWarden builds.
Additionally I updated the project docker image to allow to run this patched version cf : https://github.com/Timshel/oidc_web_builds
Cf: 
> If you want to use the version which additionally change the default redirection to /sso and fix organization invitation to persist. You need to pass an env variable: -e SSO_FRONTEND='override'

This `main` branch is lagging a bit but I will update it in the coming days.

**Comment by maxulm** [comment]
Ok, so with the timshel/sso-support branch and the docker compose it should work?
![image](https://github.com/Timshel/vaultwarden/assets/19280402/1057f0ce-00b3-42bd-a573-b61f8235f13e)

**Comment by Timshel** [comment]
It will work as in https://github.com/Timshel/vaultwarden/blob/sso-support/test/oidc/README.md : 
> To procede with an SSO login after you enter the email, on the screen prompting for Master Password the sso button should be visible.

**Comment by Timshel** [comment]
I'm unsure what you are running, this should be needed only if you are running with a front-end build from https://github.com/dani-garcia/bw_web_builds/releases

**Comment by maxulm** [comment]
I've checked out the timshel/sso-support branch, built the Dockerfile and created a container from this image with the docker compose in the screenshot.

**Comment by Timshel** [comment]
If the screenshot is your complete `docker-compose.yml` then yes it's missing a way to run the `sed`.

You can see how it's done in the keycloak [demo](https://github.com/Timshel/vaultwarden/blob/sso-support/test/oidc/docker-compose.yml#L31C26-L31C45). 
A script `/etc/vaultwarden.sh` is added as a volume and will be run by the default entrypoint.

**Comment by maxulm** [comment]
Thanks. I've added the sh-file and the line in docker-compose, but the button is still not displayed :/

**Comment by Timshel** [comment]
Is it working when using the demo `docker-compose` as describe in : https://github.com/Timshel/vaultwarden/blob/sso-support/test/oidc/README.md ?

**Comment by maxulm** [comment]
![image](https://github.com/Timshel/vaultwarden/assets/19280402/9c7d1ff4-470f-439d-b72a-7d1cd3867317)
Ah. It comes on the second screen after entering the mail address. Is there a way having the sso button prior entering a mail address?

**Comment by Timshel** [comment]
Cf: 
> With the default front-ent version the SSO login button is only visible after you enter an email address. [VaultWarden](https://github.com/dani-garcia/vaultwarden) maintainer are not keen on patching the front-end so this logic can't be changed.
> 
> I made a patched version of the front-end to remove this step available here : https://github.com/Timshel/oidc_web_builds But don't expect it to merged in the official VaultWarden builds. Additionally I updated the project docker image to allow to run this patched version cf : https://github.com/Timshel/oidc_web_builds Cf:
> 
> > If you want to use the version which additionally change the default redirection to /sso and fix organization invitation to persist. You need to pass an env variable: -e SSO_FRONTEND='override'

**Comment by maxulm** [comment]
Is there a branch / repo containing the full vaultwarden sourcecode, which I can use for building my image?
Combining the frontend-patch with the backend?

**Comment by Timshel** [comment]
The front is never in the same repo but the main branch of this repo is modified to allow to use either of the modified front : 

Cf : https://github.com/Timshel/vaultwarden/blob/main/test/oidc/README.md#switching-vaultwarden-front-end

**Comment by maxulm** [comment]
Ah, perfect! I've just used the wrong branch. Thx a lot for your support!
