### ISSUE TITLE
Only allow SSO Sign-Ups

### ISSUE THREAD

**Issue by jobritz** [Timshel/vaultwarden#61]
Hey, I know that I can disable non-SSO-logins. Would it also be possible to disable non-SSO-sign-ups? I would like to block regular sign-ups because these users are not invited in an Organization and don't have to obey the SSO master-password-policy.

Thanks in advance :)

**Comment by Timshel** [comment]
You can run with `SIGNUPS_ALLOWED=false` it will not disable SSO signups.

**Comment by jobritz** [comment]
Thanks for the hint, I had the issue because I also had another domain in the E-Mail domain whitelist which apperently overwrites the SIGNUPS_ALLOWED variable. Without the whitelist it works as expected
