### ISSUE TITLE
SSO and Organization Group Mapping

### ISSUE THREAD

**Issue by michael-harman** [Timshel/vaultwarden#64]
Hi Tim, 

I think I finally have a question that I wont magically figure out 1 hour after I leave a ticket...

Basically I am trying to get Group/Organization invitation mapping working with Keycloak.  I have a decent sized user DB being imported into keycloak from an LDAP server (this part works fine).  Where I am running into trouble is mapping those user groups to organization uuids and having them become members when they first sign in and create a vaultwarden account.

I have implemented this config as per your instructions:

# Organization Mapping and Invitation
SSO_ORGANIZATIONS_INVIT=true
SSO_ORGANIZATIONS_TOKEN_PATH=/groups
SSO_ORGANIZATIONS_ALL_COLLECTIONS=true
SSO_ORGANIZATIONS_ID_MAPPING="admins:f0c75cc2-fc39-42b5-a0d2-1f6b3464d662;"

My keycloak configuration should be appending the group information to the token as i have configured it to do so in the client scope mapper.

I am seeing no errors in the logs and the debug information doesn't show anything regarding the organization to group mapping.

Any advice would be appreciated, thanks!

**Comment by michael-harman** [comment]
[2024-06-07 02:08:35.131][vaultwarden::sso][INFO] Invitation to admins organization sent to myuser@myemail.com

Looks like its related to #48

**Comment by Timshel** [comment]
Hey,

I think you reversed the mapping and it should be : 
`SSO_ORGANIZATIONS_ID_MAPPING="f0c75cc2-fc39-42b5-a0d2-1f6b3464d662:admins"`

**Comment by michael-harman** [comment]
Should I be able to map multiple organizations and groups? For example admins to one org and moderators to another?

**Comment by michael-harman** [comment]
That worked thank you.  One last question I have and then I can close out this ticket.

Is it possible to import users and groups from SSO similar to how directory connector does where I can add users and groups to collections based off of LDAP? Thanks

**Comment by Timshel** [comment]
> Is it possible to import users and groups from SSO similar to how directory connector does where I can add users and groups to collections based off of LDAP? Thanks

Not in anything I added.

But Vaultwarden list Directory connector [as supported](https://github.com/dani-garcia/vaultwarden/wiki#supported-features)  (never tried to use it).
