### ISSUE TITLE
Setup group invitation mapping on Google Workspace

### ISSUE THREAD

**Issue by MattiaEffendi** [Timshel/vaultwarden#77]
### Vaultwarden Build Version

1.32.2-1

### Details

I don't understand how can I setup the Google directory group to Bitwarden organization mapping.
I've tried to add to the OpenID scopes the value `https://www.googleapis.com/auth/admin.directory.group.member.readonly` (which should return the user groups) but the ID token still doesn't have that value.

I still haven't tried on Bitwarden, just using the Google OAuth Playground and JWT.io to see if the ID Token contained the expected value.
Is there a guide on how to set-up this for Google? In the SSO.md file i only see it explained for Microsoft AD.

Did a little bit of searching, Google doesn't look to support in any way to return the `groups` claim in the ID token, as seen on [this issue](https://issuetracker.google.com/issues/133774835?pli=1) on their issue tracker.

The good news is, though, that there is an [endpoint](https://developers.google.com/admin-sdk/directory/reference/rest/v1/groups/list) in the Admin API that allows to get the user groups.
Do you think it would be possible in some way to generalize the group mapping implementation to call this kind of endpoints with the `access_token` provided from the IDP to get the list of groups, rather than trying to get them from the ID token?

By the way, thank you for your work. Truly an amazing effort to add the SSO feature

**Comment by MattiaEffendi** [comment]
Thank you @Timshel, that seems reasonable. Can you think of any workaround to do the group -> org mapping in any way?

**Comment by Timshel** [comment]
I never tried to use it but the [Directory Connector](https://bitwarden.com/help/directory-sync/) should allow to sync groups with an organization collections (it's listed as [supported](https://github.com/dani-garcia/vaultwarden/wiki) by Vaultwarden). It should work with [Google Workspace](https://bitwarden.com/help/workspace-directory/).
