### ISSUE TITLE
SSO_ONLY breaks mobile app sign in

### ISSUE THREAD

**Issue by developerfromjokela** [Timshel/vaultwarden#78]
### Vaultwarden Support String

-

### Vaultwarden Build Version

from docker

### Deployment method

Other method

### Reverse Proxy

apache2

### Host/Server Operating System

Linux

### Clients

Desktop

### Client Version

 2024.6.2

### Steps To Reproduce

4. Click on '...'
5. Etc '...'

### Expected Result

Login with mobile app

### Actual Result

```json
{"error":"","errorModel":{"message":"SSO sign-in is required","object":"error"},"error_description":"","exceptionMessage":null,"exceptionStackTrace":null,"innerExceptionMessage":null,"message":"SSO sign-in is required","object":"error","validationErrors":{"":["SSO sign-in is required"]}}
```

**Comment by Timshel** [comment]
Can you better describe your issue ? 

Because the error message you reference is expected since the `SSO_ONLY` setting is to force the use of SSO and the  `SSO sign-in is required` is returned when trying to authenticate with the master password.

**Comment by developerfromjokela** [comment]
The issue comes up when trying to sign in using mobile app .

**Comment by developerfromjokela** [comment]
Can there be an exception, etc. for mobile app?

**Comment by Timshel** [comment]
> Can there be an exception, etc. for mobile app?

Not sure why mobile app should be handled differently since the SSO login is working.

**Comment by developerfromjokela** [comment]
What exactly does SSO_ONLY do other than force to use SSO?

**Comment by Timshel** [comment]
nothing

**Comment by developerfromjokela** [comment]
What about not using master password?

**Comment by Timshel** [comment]
Do you mean to unlock the vault after an SSO login ?
That is not supported and not planned at the moment.

**Comment by developerfromjokela** [comment]
What about when registering with SSO, does it force user to set master
password? How does the SSO in general handle master pass?

**Comment by Timshel** [comment]
> What about when registering with SSO, does it force user to set master password ? 

yes

> How does the SSO in general handle master pass?

The SSO never see the Master password.
As to Vaultwarden outside of authentication nothing else change.
