### ISSUE TITLE
No Admin Access with SSO_ROLES_ENABLED: true

### ISSUE THREAD

**Issue by xbourcier** [Timshel/vaultwarden#81]
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.32.5-1
* Web-vault version: voidc_override-v2024.6.2-4
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.46.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://***************************",
  "domain_origin": "*****://***************************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 1440,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "debug",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "organization_invite_auto_accept": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "purge_incomplete_sso_nonce": "0 20 0 * * *",
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.eu",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://api.bitwarden.eu",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "***********************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "********************************",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_security": "off",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "sso_allow_unknown_email_verification": true,
  "sso_audience_trusted": null,
  "sso_auth_only_not_session": true,
  "sso_authority": "https://login.microsoftonline.com/************/v2.0",
  "sso_authorize_extra_params": "",
  "sso_callback_path": "https://**********/identity/connect/oidc-signin",
  "sso_client_cache_expiration": 120,
  "sso_client_id": "-----",
  "sso_client_secret": "***",
  "sso_debug_force_fail_auth_code": false,
  "sso_debug_tokens": true,
  "sso_enabled": true,
  "sso_master_password_policy": "{\"enforceOnLogin\":false,\"minComplexity\":3,\"minLength\":12,\"requireLower\":false,\"requireNumbers\":false,\"requireSpecial\":false,\"requireUpper\":false}",
  "sso_only": true,
  "sso_organizations_all_collections": true,
  "sso_organizations_id_mapping": "",
  "sso_organizations_invite": false,
  "sso_organizations_token_path": "/groups",
  "sso_pkce": true,
  "sso_roles_default_to_user": true,
  "sso_roles_enabled": false,
  "sso_roles_token_path": "roles",
  "sso_scopes": "openid profile email offline_access",
  "sso_signups_match_email": true,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "/web-vault_override",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Vaultwarden Build Version

1.32.5-1

### Deployment method

Official Container Image

### Reverse Proxy

haproxy

### Host/Server Operating System

Linux

### Operating System Version

rocky linux 8

### Clients

Web Vault

### Steps To Reproduce

Hi,

I am setting up Vaultwarden with OpenID Connect and role-based access control (RBAC) using Azure AD as the identity provider. However, I am unable to access the admin page even when the configuration seems correct

Configuration:
I am using the SSO_ROLES_TOKEN_PATH to fetch roles from the ID token. The roles claim in my ID token looks like this:

**{
  "roles": ["user", "admin"]
}**
My docker-compose.yml includes:

**SSO_ROLES_ENABLED: true
SSO_ROLES_TOKEN_PATH: "roles"
DISABLE_ADMIN_TOKEN: false**

The ID token clearly contains the roles claim with the values user and admin.
Problem:
Even when I log in with an account that has the admin role, I cannot access the admin page.
The logs repeatedly show:
**No roles in <user_email> id_token at roles**
This happens despite the roles claim being present at the root of the token.

Debugging steps so far:
Verified the ID token structure using a JWT debugger — roles are present at the root level.
Confirmed SSO_ROLES_TOKEN_PATH: "roles" matches the token's structure.
Tested both DISABLE_ADMIN_TOKEN: true and DISABLE_ADMIN_TOKEN: false.
With false, I can't access the admin page even with the correct admin role.  With true everyone access admin page
Question:
Is there something I’m missing in the configuration or in how Vaultwarden interprets SSO_ROLES_TOKEN_PATH?
Does DISABLE_ADMIN_TOKEN: false affect the role-based admin access?
Could this issue be related to Azure AD-specific behavior?
Any help would be greatly appreciated. Thank you!

### Expected Result

Only users with the admin role have access to the admin page 

### Actual Result

No one has access to the admin page.

**Comment by Timshel** [comment]
> I thought the admin token would be requested ?

Made sense to me to not require the token if you use SSO to assign roles to users.

**Comment by xbourcier** [comment]
on my side, I saw it more as a way to avoid displaying the token page if the user didn't have the admin role.

**Comment by xbourcier** [comment]
But you're right, entering the token if you're an admin doesn't make sense.

**Comment by Timshel** [comment]
> on my side, I saw it more as a way to avoid displaying the token page if the user didn't have the admin role.

I believe I modified the page to change the message but will check again.

**Comment by Timshel** [comment]
I may have misunderstood your comment, but as user the token input is not displayed and you should see:

![vw_admin](https://github.com/user-attachments/assets/dd8312ef-2b37-469f-96f7-a98f40a67e9a)
