### ISSUE TITLE
Thanks and happy holidays

### ISSUE THREAD

**Issue by tribut** [Timshel/vaultwarden#9]
Just wanted to quickly get in touch and say sorry for disappearing so suddenly from the PR. Things happened in my life that reduced the amount of time I had available considerably. Thank you for taking the initiative and moving SSO support forward. Have great holidays and lets hope that 2024 will be the year that we will finally see OIDC land in vaultwarden :)

:christmas_tree: :star2:

**Comment by Timshel** [comment]
Hey,
Thanks :smile: ,  No worry and enjoy the holidays 🎄
